##########################################################################################
#  Copyright 2022 Viacheslav Kolupaev; author's website address:
#
#   https://vkolupaev.com/?utm_source=c&utm_medium=link&utm_campaign=styleguide_config
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this
# file except in compliance with the License. You may obtain a copy of the License at
#
#   https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the specific language governing
# permissions and limitations under the License.
##########################################################################################

##########################################################################################
# `isort` configuration.
#
# Docs:
#   1. https://pycqa.github.io/isort/docs/configuration/config_files.html
#   2. https://pycqa.github.io/isort/docs/configuration/options.html
#
# GitHub: https://github.com/PyCQA/isort
#
# Issue `Enforce presence of keys (with any values)`:
#   https://github.com/andreoliwa/nitpick/issues/218
#   https://github.com/andreoliwa/nitpick/commit/506b407b5a8f6b7d5d89afe145721f7d555bb336
#
# TOML: https://github.com/toml-lang/toml
#
# The pyproject.toml file:
#   https://github.com/python-poetry/poetry/blob/master/docs/pyproject.md
#
##########################################################################################

[nitpick.meta]
name = "isort"
url = "https://github.com/PyCQA/isort"

["pyproject.toml".tool.isort]
include_trailing_comma = true
use_parentheses = true
line_length = 88
multi_line_output = 3
ensure_newline_before_comments = true
force_grid_wrap = 2
lines_before_imports = 1
lines_after_imports = 2
order_by_type = true
group_by_package = true
known_first_party = [
    "tests",
]
import_heading_future = "Future"
import_heading_stdlib = "Standard Library"
import_heading_firstparty = "First Party"
import_heading_thirdparty = "Third Party"
import_heading_localfolder = "Local Folder"
