##########################################################################################
#  Copyright 2022 Viacheslav Kolupaev; author's website address:
#
#   https://vkolupaev.com/?utm_source=c&utm_medium=link&utm_campaign=styleguide_config
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this
# file except in compliance with the License. You may obtain a copy of the License at
#
#   https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the specific language governing
# permissions and limitations under the License.
##########################################################################################

##########################################################################################
# `nitpick` configuration file.
#
# Docs: https://nitpick.readthedocs.io/en/latest/configuration.html
##########################################################################################

[nitpick]
minimum_version = "0.34.0"

[nitpick.styles]
include = [
    # common
    "commitizen.toml",
    "coveragepy.toml",
    "darglint.toml",
    "editorconfig.toml",
    "files.toml",
    "flake8.toml",
    "gitattributes.toml",
    "gitignore.toml",
    "isort.toml",
    "mypy.toml",
    "pydocstyle.toml",
    "pytest.toml",
    "python311.toml",

    # `pyproject.toml`. Order matters.
    "poetry/poetry.toml",
    "poetry/poetry_main_dependencies.toml",
    "poetry/poetry_app_dependencies.toml",
    "poetry/poetry_build_dependencies.toml",
    "poetry/poetry_dev_dependencies.toml",
    "poetry/poetry_dev_dependencies.toml",
    "poetry/poetry_lint_test_dependencies.toml",
    "poetry/poetry_type_test_dependencies.toml",
    "poetry/poetry_unit_test_dependencies.toml",
    "poetry/poetry_load_test_dependencies.toml",
]
